### ISSUE TITLE
Why does it need Administrator privilege on Windows? 

### ISSUE THREAD

**Issue by danielweiv** [Fsu0413/QQtPatcher#2]
thx

**Comment by Fsu0413** [comment]
Sorry but I didn't quite understand what you mean by "doest".
Is it typo of "doesn't" or "does"?

This program only patches Qt files from current directory. It does not need administrator privilege if Qt is installed to directory where you can read or write with administrator privilege.

(PS. I found that you have repositories with Chinese description. You can type Chinese here since I am also Chinese)

**Comment by danielweiv** [comment]
@Fsu0413 谢谢回复，我用MinGW-w64(gcc-8.1.0)静态编译Qt5.6.3之后，使用qmake编译本项目，得到的可执行程序在打开时弹出UAC要求管理员权限。同样的，如果使用qmake编译你修改过后的qtbinpatcher，运行也会要求管理员权限，但是使用cmake编译的话，就不会有此问题。我比较了你修改前后的qtbinpatcher代码，应该不是代码本身触发了UAC，可能qmake在处理.pro文件的时候添加了什么选项引出的问题。

**Comment by Fsu0413** [comment]
这个项目叫QQtPatcher，不过就算是QQtPatcher的话，需要管理员权限也不科学
我这边本地的QQtPatcher不需要管理员权限。

如果你分发了QQtPatcher的话，Windows 10会识别一部分刚刚下载下来的可执行程序，并要求使用管理员权限才能打开运行。这个是无法workaround掉的。
如果不是分发QQtPatcher的话，我只能认为是Qt5.6.3的问题了，毕竟这是2017年的东西，官方还只用MinGW gcc4.8版本来着。。。。

QQtPatcher的源码并不使用CMake，所以我无法确认CMake的实现。
qtbinpatcher我早就不用了，这个轮子无法满足我的需求。

**Comment by Fsu0413** [comment]
There were no reply since last month, I close this issue.
